### ISSUE TITLE
Cleanup UI for MVP

### ISSUE THREAD

**Issue by popic28** [rootzoll/konfetti-app#104]
Below, a list of tasks we need to cover for the UI update 

### General
- [x] integrate material design
- [ ] remove the 'tasks tab' and replace it with a 'New task' button in the 'Dashboard' tab
- [x] put neighbourhoods in a side drawer menu
- [x] rename first tab to something that suggests "tasks in current neighbourhood" but with less words
- [x] fancy icons for cell items and actions
- [ ] fancy konfetti icon to use for the konfetti counter display

#### Dashboard
- [x] remove top bar item refresh and language preference
- [x] put the title of the neighbourhood in the top bar item and current amount of konfetti info
- [ ] add a description button that takes you to a full screen description of the neighbourhood

Old :
<img width="320" alt="screen shot 2017-01-25 at 15 13 04" src="https://cloud.githubusercontent.com/assets/8224705/22293689/d7c5a216-e310-11e6-9f09-076228b04055.png">

New :
<img width="382" alt="screen shot 2017-01-25 at 15 28 49" src="https://cloud.githubusercontent.com/assets/8224705/22294286/008d109c-e313-11e6-886e-44330ed6d466.png">

#### More 
- [x] add language switch functionality here

**Comment by atzbert** [comment]
First comparison of the material design prototype with the old version showed following issues:

- [x] konfetti slider in task creation should be wider
- [x] font size in task list is too small
- [ ] no (visual) touch feedback on task list (wontfix)
- [ ] avoid frequent reloads of the task list when going back and forth (wontfix)
- [x] check the add date/image/language to task screens
- [ ] party info screen needs love
- [ ] switching parties shows the same tasks for all parties
- [ ] `item` background colour not consistent with `card`

**Comment by rootzoll** [comment]
thanks for the redesign so far. further stuff will be done on user request or with new UX design concept.
