### ISSUE TITLE
Further infrastructur work

### ISSUE THREAD

**Issue by c0nscience** [rootzoll/konfetti-app#108]
- [x] provide minimal config to launch api-service (restarts on invalid password)
- [x] get the local docker environment right -> goal is from zero to hero with just one simple commandline
- [x] clean up the rest of the jenkinsfiles
- [x] delete the docker-compose stuff from the api project, because all the stuff now lies in the serverconfig repo

**Comment by rootzoll** [comment]
- [x] automatic backup docker volume or make mySQL dump

**Comment by ppachur** [comment]
dev-setup should now be available with two commands (if api keeps crashing, remove the database-container and start over). 

Jenkins has been replaced with travis

./mvnw clean package && docker-compose up now builds all services and does not use images.
