### ISSUE TITLE
i18n - Multi Language Backend

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#11]
Although the backend has no user interface, it sends out eMails and other text that is visible to the user. Those parts of the backend need  i18n translation. I am sure Spring has something to offer here. Would be great if someone could get this started. 

Check Backend Code for TODOs containing the mention of 'multi lang' - this will quickly show you the most spots were english texts need to get  i18n.

On most API calls the client has a language code as parameter, if this is missing somehow let me know so that I can improve the API calls on the client side.

**Comment by catarata02** [comment]
okay.. habe mal was eingecheckt für die email subjects.. ist noch nicht fertig.. müsste noch velocity templates rein für die email bodyContents.. und noch nicht ganz durchgeblickt was in den subjects stehen sollte.. (timInMilliSeconds..?).. muss auf jeden Fall noch weiter dran machen.. gruss

**Comment by rootzoll** [comment]
needs testing where it already works and where we still need to implement - should be eMail and Notifications mainly

**Comment by rootzoll** [comment]
done
