### ISSUE TITLE
mixed content issue on homepage

### ISSUE THREAD

**Issue by c0nscience** [rootzoll/konfetti-app#110]
As sadly as it is to replace the cool loading cat on the homepage, but she is not secure. So we have to find another source for a funny loading cat with a secure ssl connection available to fix the mixed content issue.

**Comment by rootzoll** [comment]
I wrote an eMail to ask if we can use the cat GIF ... there is hope :D

**Comment by rootzoll** [comment]
No answer on my email. But I think I found an idea to save the cat :D

There is a service called "hideproxy.me" - with this I could proxy the HTTP cat gif link behind a HTTPS link. See here: https://proxy-de.hideproxy.me/go.php?u=CSuVyOOjihkGwJ1BsHRsQTbxmWVNKoOLpFxwHRGny03p13RurlIwQhhJBOw%3D&b=1&f=norefer

**Comment by rootzoll** [comment]
Yes it worked :D cat saved and ticket closed.

![bildschirmfoto 2017-02-12 um 15 47 41](https://cloud.githubusercontent.com/assets/2472225/22863096/b32158be-f13a-11e6-86f4-562de9caf3c1.png)

**Comment by rootzoll** [comment]
HTTPS proxy link goes dead after a while ... maybe replace with api endpoint that proxies this image? https://gifyu.com/images/ezgif.com-resize59288.gif
