### ISSUE TITLE
login button barely visible on current master

### ISSUE THREAD

**Issue by ppachur** [rootzoll/konfetti-app#119]
The placement of the login-button (login screen) is not (barely) visible. 

Bug exists only on master branch, not on deploed version. See attached screenshot.

![bildschirmfoto 2017-02-04 um 18 21 22](https://cloud.githubusercontent.com/assets/7838487/22620217/5039af8c-eb07-11e6-9493-ea8a3a968ac0.png)

**Comment by rootzoll** [comment]
Can you check again with the latest code ... I made a fix some days ago and when I call the actual version running on the server it looks fine like this:

![bildschirmfoto 2017-02-06 um 23 20 00](https://cloud.githubusercontent.com/assets/2472225/22669005/147df54e-ecc3-11e6-8dfb-6523698f616d.png)

Also looks fine on my checked out master branch.
