### ISSUE TITLE
ios: push notifications lnot working on 1.2.1

### ISSUE THREAD

**Issue by ppachur** [rootzoll/konfetti-app#136]
push notificatison dont work on current release

**Comment by rootzoll** [comment]
I took a look at our push notification provider - there are a lot of iOS devices that registered for push on the kick-off test date (25.02.) - so this error was just reduced to some phones or message delivery was not working. needs more testing.

**Comment by rootzoll** [comment]
OK es schaut, dass auf OneSignal das .p12 cert für Apple Push noch auf die alte/falsche bundle Id läuft. Das müsste upgedatet werde ... geht nur grad nicht, da AWS down ist und dort die OneSignal Doku liegt.
