### ISSUE TITLE
Arabic ??? Encoding Problem

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#17]
??? on arabic autotranslation and chat

**Comment by ppachur** [comment]
Appears to be an encoding-problem in the backend (testing-instance) MediaItemController, line 75ff. The Database was initially set to western-european. Unfortunately, changing it to utf-8 did not solve the problem immediately.  Needs further research.

**Comment by rootzoll** [comment]
@catarata02 please add to the spring boot dev-profile that it created mysql tables with default charset UTF-8 ... at the moment new tables get created with "cp1252 Western European" ... or is this a default I have to configure on the MySQL side?

**Comment by catarata02** [comment]
will be fixed with branch catarata02_fix_arabic_encoding when rolling out with new database

**Comment by catarata02** [comment]
fixed and deployed to server
