### ISSUE TITLE
Log Management

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#19]
I dont know spring boot well, is there a solution to pump the logs from running konfetti java backend into something like graylog to manage logs (warns and exception) in a comfort way? 

I started to install graylog on our dev server. https://www.digitalocean.com/community/tutorials/how-to-install-graylog2-and-centralize-logs-on-ubuntu-14-04 --> At the step to test with graylog demo "sudo java -jar /opt/graylog2-server/graylog2-server.jar --debug" shows that still not connecting to elestic search (installed before like in tutorial).

Thats were my progress on this topic ended. But would be great if someone can catch up, get graylog running and configure our konfetti app to pump logs in dev-config-profile into graylog. For dev server access contact me. 

Open to other log management solutions - if you make it run, that would be great :)

**Comment by catarata02** [comment]
graylog configured
