### ISSUE TITLE
API: Party is changing radius

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#24]
PartyController (around line 250) the personal distance to a user of a party gets calculated ... somehow, this meter distance gets written back into the object ... or at least the next time the party gets requested ... the party is delivered with a modified meter value. Find out why.

**Comment by catarata02** [comment]
pushed branch "catarata_bug_24_try_to_fix" .. please check if this works.. added transient field in "party" entity.. should be changed probably in app, to use "distanceToUser" instead of "meter"..

**Comment by catarata02** [comment]
is this one still open? if so.. how to reproduce..

**Comment by rootzoll** [comment]
i think this was related to the other radius bug - I thinks save to close.
