### ISSUE TITLE
User name and email not shown

### ISSUE THREAD

**Issue by catarata02** [rootzoll/konfetti-app#34]
If i login with email and password.. i dont see neither my email in the settings nor the username.. worse, there is a field to set an email for backup and important announcement, instead of showing my email I logged in with.

**Comment by rootzoll** [comment]
the email will now be displayed in the accounts tab. but the backend seems not to update the email - or I dont get an email to activate the change. Either way - needs to be checked on the backend side.

**Comment by catarata02** [comment]
problem was the javascript was sending email and eMail properties.. should be fixed now.. i think the username is still missing.. or did I miss it on the page?

**Comment by rootzoll** [comment]
the username (name or nickname displayed on a task) is changed on the request tab - needs to entered on first request made or first chat started.
