### ISSUE TITLE
Use GreyLog for AppError reportings

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#37]
Hey. Great to have a greylog running in our setup. Would be great to use it for error logs directly from the app running - so that we can improve the App without depending on user feedback alone.

I started to implement that: I created an input on greylog - see "System > Inputs" called "App Error Reports". Its listening already on port 12185 and I opened up the port on azure. 

But I dont get a respose to a POST call with Potman to:
http://fourcores2016.cloudapp.net:12185/gelf

I wanted to follow this tutorial: http://docs.graylog.org/en/2.1/pages/sending_data.html#gelf-via-http

I think its because the port is not routed to the correct docker container - didnt wanted to mess something up, so it would be great if can get this port open and the API call working.

If we get to this point, then it would be great to have a skype to discuss the structure of the error data send by the app, to get the best results out of it. Not a high priority, bit would be great to have this working.

**Comment by catarata02** [comment]
port is adjusted and send you an example for a post to graylog in slack..
