### ISSUE TITLE
unique users

### ISSUE THREAD

**Issue by catarata02** [rootzoll/konfetti-app#40]
Users should have unique nicknames and emails..

**Comment by rootzoll** [comment]
emails yes - related to #41 -- nicknames not sure yet. The basic use case of the app is not profile centric. To get in contact and than meet its not important that there are 10 Bobs on the app. Just the bob I meet outside the app is important. But to keep that option of building profiles later on its OK to be have this done.

**Comment by rootzoll** [comment]
There maybe one case in our app where the same usernames can be a bit of a problem. When I chatted with 3 Bobs but just two helped and I want just reward them - its maybe a bit confusing. So its not critical, but it should be implemented before final release.

**Comment by catarata02** [comment]
added unique constraint for mail on database, and checking name and email in backend for unique.. throwing BadRequest status (400) if not given.. please check in fronten.. (create user, update user)
