### ISSUE TITLE
extra info on task missing when added on creation

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#44]
On test5 step 15 the admin/clientB sees not the extra text info added by clientA on step 09. Check if this is an error on client side (not publishing or not displaying to admin) or something on the server side is missing.

**Comment by catarata02** [comment]
just was checking on this.. seems e.g. if i add a new text.. is sent to the backend and mediaItem is created, but not linked to the request.. no coupling.. lost in nirvana.. as far as I see the connection.. no other request seems to be sent to the backend after creating the text.. initially there is also no mediaItem sent... to be checked..

**Comment by rootzoll** [comment]
OK - this seems to be a client side issue then will take a look - thx
