### ISSUE TITLE
test9 step03 - first reward dialog didnt finish

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#49]
in a test run thru the first time when opening the reward dialog and selecting a the clientB, then pressing OK ... it just closed. On console there was this message: 

`Failed to load resource: the server responded with a status of 500 `

It worked in second try - check out why again while monitoring request calls on app and server.

**Comment by catarata02** [comment]
for furhter issues.. please more informations.. e.g. the log with timestamp.. then we know where to look in the log files...

**Comment by rootzoll** [comment]
Here is the first request in detail ...

![bildschirmfoto 2016-11-05 um 16 37 15](https://cloud.githubusercontent.com/assets/2472225/20031349/4d8fc808-a376-11e6-8579-e051ba30d8c9.png)

see the exception in response

![bildschirmfoto 2016-11-05 um 16 37 38](https://cloud.githubusercontent.com/assets/2472225/20031350/4f75b88a-a376-11e6-9029-283fd18bfff3.png)

when the same call is done a second time ... its working

![bildschirmfoto 2016-11-05 um 16 38 01](https://cloud.githubusercontent.com/assets/2472225/20031352/51987576-a376-11e6-95b4-8e1389e0f131.png)

**Comment by catarata02** [comment]
thx for the logs.. error is happening between line 861 and 871 .. but .. uff.. no clue where and what really is happening in there.. will see if i find out more.. has to do something with jpa persitancy.. some mandatory fields missing..

**Comment by catarata02** [comment]
just tried to reproduce this issue.. couldn't .. perhaps inconsistent data on the database.. not account more than once in the table.. or something like this.. if I cant reproduce this one, can no fix.. :/

**Comment by rootzoll** [comment]
seems OK now. Was maybe also because of too short client http timeout before. I think we can close this ticket.
