### ISSUE TITLE
eMail registration is still bad

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#56]
I tried to register a new account with the email "423424234234@trash-mail.com".

On first try I got back a "Connection Error". 
On second try it told me that the eMail is already in use.
Then I went to login screen and tried that email. Login was working.

So registration is working, but something is not working correct on the backend on to give a correct response or there is something failing in the client.

**Comment by catarata02** [comment]
Was there any error log?

**Comment by rootzoll** [comment]
strange. Ich logged into spring boot admin and to see the logs - there was a "not able to read the logs" error. After a short time the SBA was reporting an DOWN and after it was UP again, I tried again and the registration worked in the first try.

**Comment by catarata02** [comment]
Try to see if there was any error log via graylog.. Don't think anything changed in the registration process in the backend...

**Comment by rootzoll** [comment]
seems to work now  -lets close this for now
