### ISSUE TITLE
On adding a Date to Task: Time gets wrong

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#57]
It was reported that when adding a date element to a task, the time set in the dialog was not the resulting time when later displayed. Example time was 16:00 - displayed was 1:00.

**Comment by catarata02** [comment]
Guessing that the error is in the frontend.. just tested the backend:

POST:
{
  "type": "TYPE_DATE",
  "data": "\"2016-12-12T15:00:00.000Z\"",
  "comment": "test"
}

GET:
{
  "id": 72,
  "userId": 1,
  "reviewed": "REVIEWED_PRIVATE",
  "lastUpdateTS": 1481584949179,
  "comment": "test",
  "type": "TYPE_DATE",
  "data": "\"2016-12-12T15:00:00.000Z\""
}

-> the input is for time is String.. is there a certain pattern, if not matched 00:00 time is sent? just a guess..

**Comment by catarata02** [comment]
if I write in time just "16" instead of "16:00" this is sent:
{"type":"TYPE_DATE","data":"\"2016-12-12T00:00:00.000Z\"","comment":"test2"}

what about using a out-of-the-box library ..? e.g. 
https://eonasdan.github.io/bootstrap-datetimepicker/

or anything else without typing..just a idea

**Comment by catarata02** [comment]
Any progress on this?
