### ISSUE TITLE
Backend: Performant Persistence/DataServices

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#6]
In the Java Backend all Dataservices having to do with persistence are still very simple so that they just work. This would become a performance bottle neck as soon as we grow out of small beta testing. 

The task to do would go thru the data services. Search for TODOS in the code and keep eye open how to better get the results. For example in the AccountingService: If it should deliver all transactions for one user, it gets ALL transactions from the database and then filters out the ones of the user with a for-loop. There should be better ways to do this within the Spring/JDBC. To refactor this soon, would be great. Thx.

**Comment by atzbert** [comment]
Ok, ich nehme mich der Sache nächste Woche an. Kann ja nicht soooo
kompliziert sein.

Christian Rotzoll notifications@github.com schrieb am Sa., 11. Juni 2016,
13:29:

**Comment by catarata02** [comment]
hab mal einen Teil der offenen performance punkte korrigiert und gepushed.. sind aber ein paar noch offen..

**Comment by rootzoll** [comment]
super - das sieht schon mal gut aus :)

**Comment by atzbert** [comment]
still some points open. transactions need much more attention and evaluation if actually needed.
