### ISSUE TITLE
user image was not display on task

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#62]
on android I made a user selfi on my task but it was not displayed later on when the task was listed or in detail view.

**Comment by catarata02** [comment]
In the details view the image is shown.. Can you create a task with the user with the selfi to see if it works in the overview of the party?

**Comment by rootzoll** [comment]
got this fixed. on the mapping between requestVM and database request object there was missing the mapping for the mediaImageID.
