### ISSUE TITLE
eMail i18n bugs and encoding

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#70]
As can be seen in picture the i18n of the eMail is not working correct on replacement of string content ("{0}" should be replaced by name of the party) and UTF-8 encoding seems not to work - that would be very critical for emails in arab language.

![bildschirmfoto 2017-01-04 um 12 41 32](https://cloud.githubusercontent.com/assets/2472225/21641311/3cbece8c-d27b-11e6-9858-9cb3d5e2ef98.png)

**Comment by rootzoll** [comment]
found missing charset parameter - needs now testing if UTF8 works

**Comment by rootzoll** [comment]
na - email still has encoding probs. also when registering an account i get a strange eMail looking like this: 
![bildschirmfoto 2017-01-11 um 01 06 11](https://cloud.githubusercontent.com/assets/2472225/21830013/2d4756c6-d79a-11e6-9b41-fe47a16daf33.png)

**Comment by rootzoll** [comment]
maybe also check if bug comes from wrong formatted i18n files - test by sending fixed strings with umlaute and compare with strings from i18n

**Comment by rootzoll** [comment]
wrong formatted i18n files could be a thing ... because for example this text from the i18n outside of eMail also look worng:

![bildschirmfoto 2017-01-19 um 00 21 53](https://cloud.githubusercontent.com/assets/2472225/22087304/82ae1d4a-dddd-11e6-9ac2-c3eaf7ed05ff.png)

**Comment by rootzoll** [comment]
OK - I think I fixed the encoding problem. At least now the Umlaute in the Alert from server on review code entry look fine. Needs testing on email to verify.

So still the placeholders not getting value are a thing. And the Passwort Byte-Array on the one eMail above. Then we should be good on this ticket.

**Comment by c0nscience** [comment]
Found a solution: http://stackoverflow.com/a/6332640
Tried it locally and it worked.
