### ISSUE TITLE
Check that normal users dont get reviewer status

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#78]
This maybe a already solved bug but needs double checking. Testers report that they gained reviewer status and are confused that they should moderate their own tasks created. Check that just users with reviewer codes get reviewer on the parties the users are meant to be reviewers on.

**Comment by rootzoll** [comment]
I was able to reproduce. Open a fresh browser. Register with email and password. Say "Check my area" on first menu. And there is an "R" for reviewer when starting fresh in a party.

**Comment by rootzoll** [comment]
Sometimes I am not a reviewer on first party visit, but get later on somehow. This bug breaking the app user model and needs fixing.

**Comment by catarata02** [comment]
should be fixed.. please verify
