### ISSUE TITLE
PushManager.java not picking up values from .properties file

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#84]
In the PushManager.java the ID and Auth-Token should be injected from properties file:

![bildschirmfoto 2017-01-15 um 02 16 37](https://cloud.githubusercontent.com/assets/2472225/21959483/09b4d1de-dac9-11e6-9e91-3ef3635eb9c7.png)

But when outputting the values on runtime they are both null - but are are values set in the konfetti.properties file on the server (user root). Why?

**Comment by catarata02** [comment]
should be fixed now.. please verify.. branch catarata02_fix_pushManager... if all good merge into master and push..
problem was that properties dont work with singleton.. as far as I understand the Beans are singletons anyway...
