### ISSUE TITLE
Reviewercodes have no effect

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#95]
On a new user I tried a reviewer code. It came back OK after entering the code on the settings panel - givung me the following text (i18n encoding is problem on other ticket)

![bildschirmfoto 2017-01-19 um 00 21 53](https://cloud.githubusercontent.com/assets/2472225/22087362/cd0cdae8-dddd-11e6-8ae3-989176338417.png)

But had no effect. I was not reviewer on that party. When looking at the 'actions' on the returned htto-request, they were also empty.

![bildschirmfoto 2017-01-19 um 00 26 30](https://cloud.githubusercontent.com/assets/2472225/22087397/fd75b0ba-dddd-11e6-81bb-88cbb7641145.png)

Need to check this out.

**Comment by catarata02** [comment]
is related to bug #78 should be fixed now.. please check and verify after fix for bug #78 is deployed on production
